// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkH5XebSTFsHQrNH52CZ5segEF3aqnPmw',
    appId: '1:961923631685:web:ed99328d23bdd74c86b12c',
    messagingSenderId: '961923631685',
    projectId: 'social-media-fb630',
    authDomain: 'social-media-fb630.firebaseapp.com',
    databaseURL: 'https://social-media-fb630-default-rtdb.firebaseio.com',
    storageBucket: 'social-media-fb630.appspot.com',
    measurementId: 'G-20RJP6YDYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5dImKT1zrIvmpGOAWMxoovWcnSxGLGTs',
    appId: '1:961923631685:android:f796c4d55bedfe4686b12c',
    messagingSenderId: '961923631685',
    projectId: 'social-media-fb630',
    databaseURL: 'https://social-media-fb630-default-rtdb.firebaseio.com',
    storageBucket: 'social-media-fb630.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGIWLQLDeND2TgwdZL2g2VxXdhppKn_iI',
    appId: '1:961923631685:ios:1255cdfaf6c34e8786b12c',
    messagingSenderId: '961923631685',
    projectId: 'social-media-fb630',
    databaseURL: 'https://social-media-fb630-default-rtdb.firebaseio.com',
    storageBucket: 'social-media-fb630.appspot.com',
    iosClientId: '961923631685-62te8e5cs5q0i299e4d4qperokba40fn.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );
}
